version = 0.1
[default.deploy.parameters]
stack_name = "dauntless"
resolve_s3 = true
s3_prefix = "dauntless"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
