AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Dauntless is a message broker based on HTTP

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  DauntlessLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dauntless
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java21
      MemorySize: 512
      Architectures:
        - arm64
      SnapStart:
        ApplyOn: PublishedVersions
      CodeUri: ./build/libs/dauntless-lambda.jar
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Environment:
        Variables:
          MAIN_CLASS: portfolio.dauntless.DauntlessApplication
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /api/hello
            Method: GET
            TimeoutInMillis: 10000
        Uppercase:
          Type: Api
          Properties:
            Path: /api/uppercase
            Method: GET
            TimeoutInMillis: 10000

Outputs:
  DauntlessLambdaARN:
    Description: Lambda Function ARN
    Value: !GetAtt DauntlessLambda.Arn
#  ContentBucketName:
#    Description: "S3 bucket for uploading CloudFront content"
#    Value: !Ref ContentBucket
