spring:
  application:
    name: dauntless
  profiles:
    active: local
  cloud:
    function:
      definition: requestRouter

springdoc:
  version: '1.0.0'

swagger:
  server:
    url: 'http://localhost:8080'
